FROM node:12

# Create our application directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install Screwdriver Store
COPY . /usr/src/app
RUN npm install --production

# Setup configuration folder
RUN ln -s /usr/src/app/node_modules/screwdriver-store/config /config

# Expose the web service port
EXPOSE 80

# Run the service
CMD [ "npm", "start" ]
