FROM node:12

# Create our application directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install Screwdriver Store
COPY . /usr/src/app
RUN npm install --production

# Expose the web service port
EXPOSE 80

# Run the service
CMD [ "npm", "start" ]
