shared:
    image: node:12

jobs:
    main:
        environment:
            SD_SONAR_OPTS: "-Dsonar.sources=lib,plugins,helpers -Dsonar.tests=test -Dsonar.javascript.lcov.reportPaths=artifacts/coverage/lcov.info -Dsonar.testExecutionReportPaths=artifacts/report/test.xml"
        requires: [~pr, ~commit]
        steps:
            - install: npm install
            - test: npm test

    # Publish the package to GitHub and build Docker image
    publish:
        requires: [main]
        template: screwdriver-cd/semantic-release
        steps:
          - postpublish: |
                git clone https://github.com/screwdriver-cd/toolbox.git ci
                git fetch
                export DOCKER_TAG=`git describe --tags`
                ./ci/docker-trigger.sh
        environment:
            # Docker hub repo
            DOCKER_REPO: screwdrivercd/store
        secrets:
            # Publishing to NPM
            - NPM_TOKEN
            # Pushing tags to Git
            - GH_TOKEN
            # Trigger a Docker Hub build
            - DOCKER_TRIGGER

    # Deploy to beta environment and run tests
    beta:
        requires: [publish]
        steps:
            - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
            - get-tag: ./ci/git-latest.sh
            - wait-docker: DOCKER_TAG=`cat VERSION` ./ci/docker-wait.sh
            - deploy-k8s: K8S_TAG=`cat VERSION` ./ci/k8s-deploy.sh
            - test: sleep 20 && curl --silent --fail -o /dev/null https://beta.store.screwdriver.cd/v1/status
        environment:
            DOCKER_REPO: screwdrivercd/store
            K8S_CONTAINER: screwdriver-store
            K8S_IMAGE: screwdrivercd/store
            K8S_HOST: kubernetes
            K8S_DEPLOYMENT: sdstore-beta
            SD_STORE: beta.store.screwdriver.cd
        secrets:
            # Talking to Kubernetes
            - K8S_TOKEN

    # Deploy to prod environment and run tests
    prod:
        requires: [beta]
        steps:
            - setup-ci: git clone https://github.com/screwdriver-cd/toolbox.git ci
            - get-tag: ./ci/git-latest.sh
            - wait-docker: DOCKER_TAG=`cat VERSION` ./ci/docker-wait.sh
            - deploy-k8s: K8S_TAG=`cat VERSION` ./ci/k8s-deploy.sh
            - test: sleep 20 && curl --silent --fail -o /dev/null https://store.screwdriver.cd/v1/status
        environment:
            DOCKER_REPO: screwdrivercd/store
            K8S_CONTAINER: screwdriver-store
            K8S_IMAGE: screwdrivercd/store
            K8S_HOST: kubernetes
            K8S_DEPLOYMENT: sdstore
            SD_STORE: store.screwdriver.cd
        secrets:
            # Talking to Kubernetes
            - K8S_TOKEN
